### ISSUE TITLE
LoSoTo v2.1 removed from pip

### ISSUE THREAD

**Issue by sarusso** [revoltek/losoto#116]
pip output:

`ERROR: Could not find a version that satisfies the requirement losoto==2.1 (from versions: 2.2, 2.2.1)
`

..why? We were just ok with version 2.1.

Moreover, newer versions have the `python-casacore` requirement which is forcing us to refactor our containers.

**Comment by gmloose** [comment]
As far as I know, there has never been a 2.1 version on PyPI. The first "official" release on PyPI is version 2.2.
The `python-casacore` dependency is there because some parts depend on `casacore` unconditionally. 
You don't have to install from PyPI. You can always directly install from the git repository, and specify 2.1 as the version you want.
```
pip install git+https://github.com/revoltek/losoto.git@2.1
```

**Comment by sarusso** [comment]
Ok, maybe one of the packages we installed in their early versions were doing what you suggest here in their requirements an we didn't notice

Thank you for the hint!
Closing the ticket.
