### ISSUE TITLE
always work on log(amplitude)

### ISSUE THREAD

**Issue by rvweeren** [revoltek/losoto#74]
Smoothing, median, filtering, means, etc. should always be done in log(amplitude) space. 

For example, the mean of amplitude 0.1 and 10.0 is 1.0 (not 5.05). This creates biases if operations are not done in  log(amplitude) space. Our older scripts did do that but now it seems that got lost when we moved to losoto.....

**Comment by Joshuaalbert** [comment]
In fact, it can be shown that you must do this. This is done by considering wave propagation in an inhomogeneous medium with the JWKB approximation (up to first order -- assuming refractive index variations are on lengthscales are much larger than the wavelength), in the Fresnel regime (assuming you can treat wave propagation as ray propagation). When you do this, and consider the evolution of the real and imaginary parts of the wave state you find that they correspond to log (amplitude) and classical phase deviation. See e.g. equation 16 in https://nvlpubs.nist.gov/nistpubs/jres/66D/jresv66Dn5p621_A1b.pdf.

Then, any correlations that you measure of the wave state (like electric field correlations) must be done in the appropriate measure. The simplest is in real and imaginary parts because they are additive spaces I.e. If you want to additively smooth the amplitude you must take the log.

**Comment by revoltek** [comment]
Ok, I need some time to fix these things, thanks for pointing them out

**Comment by Joshuaalbert** [comment]
FYI, The most unbiased way would be to make the transform:
```
A -> log(A/median(A))
```
not with `mean(A)`

**Comment by revoltek** [comment]
we transform from A -> log10(A) if it is amplitude before performing the various operation, I don't get what do you mean.

BTW, I'm checking the operation, all flagging operation were already correct. I think the only problem is in the smooth operation. @darafferty is the interpolation operation doing it right?

**Comment by revoltek** [comment]
I added a "log" option in the clip and smooth operation. If amplitude is detected without the log option there's a warning. Is that ok?

**Comment by rvweeren** [comment]
Ah, so it's seems only the smoothing then.

Maybe make the log default, I do not see you would not want use the log. (if you work on amplitudes)
