### ISSUE TITLE
Difference expion and normal clock/tec fitting?

### ISSUE THREAD

**Issue by tikk3r** [revoltek/losoto#80]
I just noticed this warning for the clock/TEC separation
https://github.com/revoltek/losoto/blob/3de92c9adbe243aa88e5cc189816e9dbcf03fa01/losoto/operations/_fitClockTEC.py#L9-L16

Currently I do not have the `lofar.expion` module installed, is there a major difference in the result obtained between the two? Is it better to use `lofar.expion`?

**Comment by maaijke** [comment]
There is some old c code by Bas in expion that is used to remove 2pi phase wraps. I don't think it matters too much if it is missing, but I still need to test/rewrite this. If you notice 2pi phase jumps please let me know.

**Comment by rvweeren** [comment]
I think there is a problem with the code in losoto for clock-TEC fitting. For the international stations in particular I get rather large differences with my own code (this is for 3C147 for which which is very compact). I have looked in detail  at how my own (brute force search) performed and the fits I can produce look very clean, see attached example for UK608HBA.
![c1](https://user-images.githubusercontent.com/3879473/63424964-caf33200-c40f-11e9-84b7-50dc89a480dd.png). I also get very consistent results as a function of time (without propagating any knowledge about the clock from previous time steps). Attached tables show the differences between my fitting and prefactor3 (losoto). The input phases are identical in this experiment. Note the 30ns difference for UK608HBA for example. My impression is that for international stations losoto clock-TEC fitting is not to be trusted. For the remote stations there is better agreement, although not for RS210HBA. Speculating here, but it seems when there are a lot of phase wraps across the frequency band (either caused by large dTEC and/or large clock) the losoto implementation gives unstable results, I guess we need some insight from @maaijke here what is going on in losoto.

Clocks values: my code  vs  losoto 
Antenna CS001HBA0 [ns] 00.0     00.8
Antenna CS001HBA1 [ns] -0.0     00.6
Antenna CS002HBA0 [ns] -1.0     00.3
Antenna CS002HBA1 [ns] -1.0     00.4
Antenna CS003HBA0 [ns] 00.1     01.1
Antenna CS003HBA1 [ns] -0.5     01.0
Antenna CS004HBA0 [ns] -0.9     -0.6
Antenna CS004HBA1 [ns] -0.9     -0.7
Antenna CS005HBA0 [ns] -1.0     -0.1
Antenna CS005HBA1 [ns] 00.7     00.2
Antenna CS006HBA0 [ns] -2.7     -0.8
Antenna CS006HBA1 [ns] -1.5     -0.4
Antenna CS007HBA0 [ns] -1.7     01.6
Antenna CS007HBA1 [ns] 00.7     01.9
Antenna CS011HBA0 [ns] 00.4     01.2
Antenna CS011HBA1 [ns] 00.8     01.4
Antenna CS013HBA0 [ns] -0.8     00.4
Antenna CS013HBA1 [ns] -0.7     00.1
Antenna CS017HBA0 [ns] 01.8     00.9
Antenna CS017HBA1 [ns] 02.0     00.9
Antenna CS021HBA0 [ns] -1.4     00.2
Antenna CS021HBA1 [ns] -1.7     00.1
Antenna CS024HBA0 [ns] 00.4     00.5
Antenna CS024HBA1 [ns] 00.2     00.3
Antenna CS026HBA0 [ns] 00.8     00.2
Antenna CS026HBA1 [ns] 01.9     00.3
Antenna CS028HBA0 [ns] -0.9     00.7
Antenna CS028HBA1 [ns] -0.9     00.8
Antenna CS030HBA0 [ns] -1.3     00.2
Antenna CS030HBA1 [ns] -0.3     00.2
Antenna CS031HBA0 [ns] 00.1     00.4
Antenna CS031HBA1 [ns] 00.0     00.3
Antenna CS032HBA0 [ns] -2.8     -0.3
Antenna CS032HBA1 [ns] -2.4     -0.3
Antenna CS101HBA0 [ns] 01.9     01.7
Antenna CS101HBA1 [ns] 01.4     01.8
Antenna CS103HBA0 [ns] -1.6     00.1
Antenna CS103HBA1 [ns] -1.1     00.3
Antenna CS201HBA0 [ns] 00.6     00.1
Antenna CS201HBA1 [ns] 00.9     00.2
Antenna CS301HBA0 [ns] -2.7     -0.7
Antenna CS301HBA1 [ns] -2.9     -0.8
Antenna CS302HBA0 [ns] -2.9     -2.1
Antenna CS302HBA1 [ns] -3.1     -2.0
Antenna CS401HBA0 [ns] -2.1     -0.3
Antenna CS401HBA1 [ns] -1.9     -0.2
Antenna CS501HBA0 [ns] -1.1     00.4
Antenna CS501HBA1 [ns] -0.7     00.3
Antenna DE601HBA [ns] 153.5     143.4
Antenna DE602HBA [ns] 95.4     116.2
Antenna DE603HBA [ns] 38.9     50.3
Antenna DE604HBA [ns] 08.9     14.6
Antenna DE605HBA [ns] 133.4     119.7
Antenna DE609HBA [ns] 136.5     127.5
Antenna FR606HBA [ns] 49.4     49.1
Antenna IE613HBA [ns] 201.0     259.4
Antenna PL610HBA [ns] 117.3     122.0
Antenna PL611HBA [ns] 115.3     136.5
Antenna PL612HBA [ns] 172.6     194.6
Antenna RS106HBA [ns] 91.5     91.0
Antenna RS205HBA [ns] 48.9     47.4
Antenna RS208HBA [ns] 03.7     00.6
Antenna RS210HBA [ns] 26.9     16.9
Antenna RS305HBA [ns] -26.5     -26.7
Antenna RS306HBA [ns] 50.3     51.6
Antenna RS307HBA [ns] 03.7     04.0
Antenna RS310HBA [ns] 69.2     67.0
Antenna RS406HBA [ns] -14.7     -13.4
Antenna RS407HBA [ns] 24.7     26.2
Antenna RS409HBA [ns] -57.5     -57.1
Antenna RS503HBA [ns] 11.7     13.3
Antenna RS508HBA [ns] 76.9     77.4
Antenna RS509HBA [ns] 18.3     19.3
Antenna SE607HBA [ns] 135.0     165.1
Antenna UK608HBA [ns] 195.9     226.1

**Comment by maaijke** [comment]
I never tested the clock/TEC fitting for international stations that well, it is very well possible that I introduced some constraints on the maximum clock/TEC error that are too limiting for international baselines. I'll check the code

**Comment by maaijke** [comment]
preferably  I would like to check with a test data set, is it available?

**Comment by adrabent** [comment]
Data is available here:
https://github.com/lofar-astron/prefactor/issues/246#issuecomment-522911998

**Comment by rvweeren** [comment]
@maaijke here it is: ftp://ftp.strw.leidenuniv.nl/pub/vanweeren/3C147sols.tar

```
from losoto.h5parm import h5parm
ionmodel = h5parm('your.h5' ,readonly=True)
phases = ionmodel.getSolset('sol000').getSoltab('phaseOrig').getValues()[0]

```

**Comment by maaijke** [comment]
THis is what I get with updated code, it matches within 5ns for most stations, some international stations have up to 12 ns difference with Reinout's values and DE609 was completely flagged by my code,not sure why
DE601HBA 154.312228858
DE602HBA 95.3757242333
DE603HBA 39.1800470728
DE604HBA 8.6023567523
DE605HBA 133.674348689
DE609HBA -0.797737660189
FR606HBA 61.0047959787
IE613HBA 199.496841769
PL610HBA 114.923984678
PL611HBA 121.454441304
PL612HBA 158.251097171
RS106HBA 91.4082647465
RS205HBA 47.4161559107
RS208HBA 3.09539659848
RS210HBA 27.7960786442
RS305HBA -27.7922266628
RS306HBA 50.3892301183
RS307HBA 3.77804426503
RS310HBA 69.5953302597
RS406HBA -15.6715234869
RS407HBA 23.40749444
RS409HBA -57.6347815553
RS503HBA 12.0971653489
RS508HBA 73.8167627551
RS509HBA 17.6958890232
SE607HBA 139.561715182
UK608HBA 199.305817091

**Comment by rvweeren** [comment]
Good to see there is more agreement. This also improves the match for RS210HBA.

**Comment by maaijke** [comment]
DE601HBA 154.312431546
DE602HBA 95.3759269214
DE603HBA 39.1802497609
DE604HBA 8.60255944035
DE605HBA 133.674551377
DE609HBA 135.893025007
FR606HBA 49.0215991851
IE613HBA 197.784732197
PL610HBA 114.924381178
PL611HBA 109.584738945
PL612HBA 153.115400473
RS106HBA 91.8995405959
RS205HBA 47.3285615817
RS208HBA 2.72235611831
RS210HBA 26.0841258481
RS305HBA -28.241247596
RS306HBA 49.8305557491
RS307HBA 2.98190822627
RS310HBA 69.5957617188
RS406HBA -15.3207675028
RS407HBA 24.2052171395
RS409HBA -57.6341162802
RS503HBA 12.1899248288
RS508HBA 75.6744331754
RS509HBA 17.6960917112
SE607HBA 136.137901813
UK608HBA 195.882102724

results of latest commit. Only PL612 still shows a larger offset, I get a lot of bad datapoints for this one

**Comment by rvweeren** [comment]
PL612 has the noisiest solutions and might also be somewhat affected by assumptions about the source structure (used a point source model which is a bit of a simplification). Therefore I think the difference for PL612 is acceptable in particular because I do a free 3 parameters fit (which can absorb more source structure).
